-- ExamPrepPlus Database Migration
-- Generated by Drizzle Kit
-- Apply this in Supabase SQL Editor: https://app.supabase.com/project/lynpwgioyhfqdlchkbfd/sql

-- Create all ENUM types
CREATE TYPE IF NOT EXISTS "public"."subscription_status" AS ENUM('free', 'active', 'expired', 'cancelled');
CREATE TYPE IF NOT EXISTS "public"."user_role" AS ENUM('user', 'admin');
CREATE TYPE IF NOT EXISTS "public"."exam_type" AS ENUM('RRB_NTPC', 'SSC_CGL', 'BANK_PO', 'OTHER');
CREATE TYPE IF NOT EXISTS "public"."difficulty_level" AS ENUM('easy', 'medium', 'hard');
CREATE TYPE IF NOT EXISTS "public"."test_type" AS ENUM('mock', 'live', 'sectional', 'practice');
CREATE TYPE IF NOT EXISTS "public"."attempt_status" AS ENUM('in_progress', 'submitted', 'auto_submitted');
CREATE TYPE IF NOT EXISTS "public"."payment_status" AS ENUM('pending', 'completed', 'failed', 'refunded');
